// Mock data for deep_Admin. Phase 1 model:
// product page links reference TourOptions; display content lives on the TourOption.
window.SEED = {
  tourOption: {
    id: "to_01J7KYO3PR",
    code: "G-KYO-003-1-PR",
    theme: "京都ナイトフードツアー",
    name: "祇園ナイトフードツアー 貸切3時間",
    officialName: "Kyoto Gion Night Food Tour - Private 3h",
    selectionName: "貸切3時間プラン",
    shortDescription: "祇園周辺をガイドと歩く、少人数向けの夜ツアー。",
    detailDescription:
      "地元の飲食店を巡りながら、祇園の街並みと食文化を楽しむプランです。初めて京都を訪れるゲストにも案内しやすい内容にしています。",
    tags: ["貸切", "夜", "人気"],
    type: "ガイドツアー",
    category: "Food & Drink",
    prefecture: "京都府",
    city: "京都市",
    area: "祇園・東山",
    duration: "3時間",
    minBooking: "1",
    maxBooking: "8",
    capacity: "8",
    meetingPlace: "京阪祇園四条駅 6番出口",
    meetingPlaceEn: "Keihan Gion-Shijo Station Exit 6",
    mapUrl: "https://maps.google.com/",
    pickup: "なし",
    dropoff: "祇園周辺",
    guestSchedule:
      "集合、祇園散策、飲食店2から3軒、八坂神社周辺で解散。混雑状況により訪問順を調整します。",
    inclusions: "英語ガイド、軽食、飲み物1杯、訪問先案内",
    exclusions: "追加飲食代、ホテル送迎、交通費",
    cutoff: "24時間前まで予約可能",
    cancelPolicy: "24時間前まで無料キャンセル",
    freeCancelDeadline: "24時間前まで無料キャンセル",
    cancellationFeeRate: 100,
    nonRefundable: false,
    nonRefundableNote: "",
    reschedulePolicy: "要相談",
    exceptionalRefundMemo: "台風・大雨などの天候警報発令時は運営判断で全額返金対応。ガイド都合の催行中止も同様。",
    cancelInternalMemo: "繁忙期（11月）は無料キャンセル期限を48時間前に変更する運用を検討中。",
    price: "¥18,000",
    costCheck: "原価確認済み",
    guideMemo: "夜間の混雑と雨天時ルートを事前確認。食事制限は前日までに確認。",
    salesStatus: "掲載中",
    tieredPricingEnabled: true,
    tieredPrices: [
      { id: "tp-1", min: 1, max: 2, price: 10000, openMax: false },
      { id: "tp-2", min: 3, max: 5, price: 8000, openMax: false },
      { id: "tp-3", min: 6, max: null, price: 7000, openMax: true },
    ],
    pricingCategories: [
      {
        id: "pc-adult",
        name: "大人",
        basePrice: 18000,
        costPrice: 8000,
        tieredEnabled: true,
        tiers: [
          { id: "tp-1", min: 1, price: 10000 },
          { id: "tp-2", min: 3, price: 8000 },
          { id: "tp-3", min: 6, price: 7000 },
        ],
      },
      {
        id: "pc-child",
        name: "小人",
        basePrice: 9000,
        costPrice: 4000,
        tieredEnabled: false,
        tiers: [],
      },
    ],
  },

  productPage: {
    id: "pg_01KYOTOFOOD",
    name: "京都ナイトフードツアー商品ページ",
    url: "/tours/kyoto-night-food",
    pageType: "通常商品ページ",
    category: "Food & Drink",
    prefecture: "京都府",
    city: "京都市",
    area: "祇園・東山",
    displayTitle: "京都の夜を歩くフードツアー",
    subtitle: "祇園の街並みと地元の味を、ガイドと一緒に楽しむ夜の体験",
    template: "標準商品ページ",
    optionLayout: "標準リスト型",
    defaultLinkId: "link-01",
    lead:
      "初めての京都でも歩きやすい祇園エリアで、食事と街歩きを組み合わせたガイド付きツアーです。",
    overview:
      "夜の街並みを楽しみながら、地元の飲食店や歴史ある通りを巡ります。貸切とグループのTourOptionを同じ商品ページで選択できます。",
    points: "英語ガイド、駅近集合、雨天時ルートあり、少人数対応",
    audience: "京都が初めての旅行者、夜の街歩きを楽しみたいゲスト",
    cautions: "歩きやすい靴で参加。飲食店の混雑により順番が変わる場合があります。",
    includedNote: "ガイド、軽食、飲み物1杯",
    excludedNote: "追加注文、ホテル送迎、交通費",
    status: "掲載中",
  },

  // Phase 1: link records only manage display order / default / visibility / sellability / note.
  // Display content (selectionName, price, tags, short description) is read from the TourOption.
  tourOptionsLookup: {
    "G-KYO-003-1-PR": {
      selectionName: "貸切3時間プラン",
      shortDescription: "祇園周辺をガイドと歩く、少人数向けの夜ツアー。",
      tags: ["貸切", "夜", "人気"],
      price: "¥18,000",
      duration: "3時間",
      capacity: "1〜8名",
    },
    "G-KYO-003-1-GR": {
      selectionName: "グループ3時間プラン",
      shortDescription: "他のゲストと一緒に参加する、グループ向けの夜ツアー。",
      tags: ["グループ", "夜", "定番"],
      price: "¥12,000",
      duration: "3時間",
      capacity: "2〜12名",
    },
    "G-KYO-003-2-PR": {
      selectionName: "貸切4時間プラン",
      shortDescription: "食事時間を長めに確保した、4時間の貸切プラン。",
      tags: ["貸切", "夜", "準備中"],
      price: "¥24,000",
      duration: "4時間",
      capacity: "1〜6名",
    },
  },

  linkedOptions: [
    {
      id: "link-01",
      order: 1,
      default: true,
      visible: true,
      sellable: true,
      tourOptionId: "to_01J7KYO3PR",
      code: "G-KYO-003-1-PR",
      note: "",
      salesStatus: "販売ON",
    },
    {
      id: "link-02",
      order: 2,
      default: false,
      visible: true,
      sellable: true,
      tourOptionId: "to_01J7KYO3GR",
      code: "G-KYO-003-1-GR",
      note: "",
      salesStatus: "販売ON",
    },
    {
      id: "link-03",
      order: 3,
      default: false,
      visible: true,
      sellable: false,
      tourOptionId: "to_01J7KYO4PR",
      code: "G-KYO-003-2-PR",
      note: "販売開始前の確認中",
      salesStatus: "販売OFF",
    },
  ],

  guideDocs: [
    {
      id: "doc-001",
      type: "参考資料",
      scope: "共通",
      name: "祇園・東山エリア 観光基礎資料",
      docType: "観光情報",
      url: "https://drive.google.com/sample-kyoto-area",
      content: "祇園・東山エリアの主要スポット解説。花見小路・石塀小路の歴史的背景と案内ポイントを記載。",
      cautions: "週末夜の混雑に注意。観光客への写真撮影マナーを案内すること。",
      note: "2026年3月更新版",
      assignedTo: ["G-KYO-003-1-PR", "G-KYO-003-1-GR", "G-KYO-003-2-PR"],
    },
    {
      id: "doc-002",
      type: "注意事項",
      scope: "共通",
      name: "飲食店 アレルギー確認手順",
      docType: "運営注意",
      url: "",
      content: "全ツアー共通のアレルギー確認フロー。前日までにゲストへ確認し、当日店舗スタッフに伝える手順。",
      cautions: "グルテン・甲殻類のアレルギーは特に注意。確認漏れがあった場合は運営に即報告。",
      note: "",
      assignedTo: ["G-KYO-003-1-PR", "G-KYO-003-1-GR"],
    },
    {
      id: "doc-003",
      type: "参考資料",
      scope: "個別",
      name: "G-KYO-003-1-PR 貸切プラン専用ガイドノート",
      docType: "運営注意",
      url: "https://drive.google.com/sample-private-plan",
      content: "貸切3時間プランのオペレーション詳細。雨天時の代替ルートと店舗変更手順を記載。",
      cautions: "雨天時はルート2を使用。事前に代替店舗へ連絡すること。",
      note: "貸切プラン専用",
      assignedTo: ["G-KYO-003-1-PR"],
    },
    {
      id: "doc-004",
      type: "注意事項",
      scope: "個別",
      name: "G-KYO-003-1-GR グループプラン 集合注意",
      docType: "運営注意",
      url: "",
      content: "グループプランは複数組が集合するため、名前確認と人数確認を集合時に徹底。",
      cautions: "同日同時刻に別ツアーが同じ集合場所を使う場合あり。混同に注意。",
      note: "",
      assignedTo: ["G-KYO-003-1-GR"],
    },
    {
      id: "doc-005",
      type: "参考資料",
      scope: "個別",
      name: "G-KYO-003-1-PR 貸切3時間プラン 行程",
      docType: "行程",
      url: "https://drive.google.com/sample-itinerary-pr",
      content:
        "【集合】18:00 京阪祇園四条駅6番出口\n→ 【①】18:10 花見小路散策（約20分）\n→ 【②】18:30 居酒屋Aで前菜・日本酒（約45分）\n→ 【③】19:15 石塀小路夜景散策（約15分）\n→ 【④】19:30 バーBでカクテル（約30分）\n→ 【⑤】20:00 八坂神社周辺散策（約20分）\n→ 【解散】20:20 八坂神社付近",
      cautions: "雨天時は行程②→④→③に変更。店舗変更が発生する場合は事前連絡必須。",
      note: "貸切プラン専用行程。ゲスト向けスケジュールとは別に管理。",
      assignedTo: ["G-KYO-003-1-PR"],
    },
  ],

  tabs: {
    tourOption: [
      ["basic", "基本情報"],
      ["conditions", "提供条件"],
      ["sales", "販売条件"],
      ["content", "コンテンツ"],
      ["ops", "運営・確認"],
      ["channels", "チャネル別URL"],
    ],
    productPage: [
      ["pageBasic", "ページ基本"],
      ["pageContent", "共通コンテンツ"],
      ["links", "掲載TourOption"],
    ],
    guideDoc: [
      ["docList", "資料一覧"],
      ["docDetail", "資料詳細"],
      ["docLinks", "TourOption割り当て"],
    ],
    cancelTemplate: [
      ["tmplList", "テンプレート一覧"],
      ["tmplDetail", "テンプレート編集"],
    ],
  },

  // Channel master ────────────────────────────────────────────────
  channelMaster: [
    { code: "viator",       name: "Viator",       hint: "OTA · TripAdvisor傘下" },
    { code: "getyourguide", name: "GetYourGuide", hint: "OTA · 欧州系" },
    { code: "klook",        name: "Klook",        hint: "OTA · アジア系" },
    { code: "airbnb",       name: "Airbnb Experiences", hint: "OTA · 体験" },
    { code: "expedia",      name: "Expedia / Activities", hint: "OTA" },
    { code: "own",          name: "自社サイト",   hint: "商品ページから自動取得" },
  ],

  channelUrls: [
    {
      id: "ch-01",
      channel: "Viator",
      url: "https://www.viator.com/tours/Kyoto/Kyoto-Gion-Night-Food-Tour/d332-12345P1",
      enabled: true,
      updatedAt: "2024/01/15",
      auto: false,
    },
    {
      id: "ch-02",
      channel: "GetYourGuide",
      url: "https://www.getyourguide.com/kyoto-l96779/gion-night-food-tour-t123456/",
      enabled: true,
      updatedAt: "2024/01/15",
      auto: false,
    },
    {
      id: "ch-03",
      channel: "Klook",
      url: "",
      enabled: false,
      updatedAt: "",
      auto: false,
    },
    {
      id: "ch-04",
      channel: "自社サイト",
      url: "自動取得（商品ページから）",
      enabled: null,
      updatedAt: "",
      auto: true,
    },
  ],

  // List page samples ─────────────────────────────────────────────
  tourOptionList: [
    {
      id: "to_01J7KYO3PR",
      code: "G-KYO-003-1-PR",
      name: "祇園ナイトフードツアー 貸切3時間",
      theme: "京都ナイトフードツアー",
      tags: ["貸切", "夜", "人気"],
      salesStatus: "掲載中",
      price: "¥18,000",
      priceValue: 18000,
      updatedAt: "2026-05-22",
      checksPassed: true,
    },
    {
      id: "to_01J7KYO3GR",
      code: "G-KYO-003-1-GR",
      name: "祇園ナイトフードツアー グループ3時間",
      theme: "京都ナイトフードツアー",
      tags: ["グループ", "夜", "定番"],
      salesStatus: "掲載中",
      price: "¥12,000",
      priceValue: 12000,
      updatedAt: "2026-05-21",
      checksPassed: true,
    },
    {
      id: "to_01J7KYO4PR",
      code: "G-KYO-003-2-PR",
      name: "祇園ナイトフードツアー 貸切4時間",
      theme: "京都ナイトフードツアー",
      tags: ["貸切", "夜", "準備中"],
      salesStatus: "非公開",
      price: "¥24,000",
      priceValue: 24000,
      updatedAt: "2026-05-18",
      checksPassed: false,
    },
    {
      id: "to_01J7ASA1PR",
      code: "G-OSK-005-1-PR",
      name: "大阪ストリートフード 貸切2時間",
      theme: "大阪ストリートフード",
      tags: ["貸切", "昼", "新着"],
      salesStatus: "下書き",
      price: "¥14,000",
      priceValue: 14000,
      updatedAt: "2026-05-15",
      checksPassed: false,
    },
  ],

  productPageList: [
    {
      id: "pg_01KYOTOFOOD",
      url: "/tours/kyoto-night-food",
      displayTitle: "京都の夜を歩くフードツアー",
      status: "掲載中",
      linkedTotal: 3,
      linkedVisible: 3,
      linkedSellable: 2,
    },
    {
      id: "pg_01KYOTOTEMPLE",
      url: "/tours/kyoto-temple-morning",
      displayTitle: "早朝の京都古寺めぐり",
      status: "非公開",
      linkedTotal: 2,
      linkedVisible: 1,
      linkedSellable: 0,
    },
    {
      id: "pg_01OSAKAFOOD",
      url: "/tours/osaka-street-food",
      displayTitle: "大阪ストリートフード食べ歩き",
      status: "下書き",
      linkedTotal: 0,
      linkedVisible: 0,
      linkedSellable: 0,
    },
  ],

  cancelTemplates: [
    {
      id: "ct_01_NONREF",
      name: "全額返金不可",
      lang: "日本語",
      enabled: true,
      body: "本商品は返金不可です。予約確定後のキャンセル・日程変更はお受けできません。",
      note: "",
      updatedAt: "2024/01/15",
    },
    {
      id: "ct_02_2DAY",
      name: "２日前までは全額返金が可能",
      lang: "日本語",
      enabled: true,
      body: "体験開始の２日前まで全額返金いたします。それ以降のキャンセルは返金不可となります。",
      note: "",
      updatedAt: "2024/01/15",
    },
    {
      id: "ct_03_7DAY",
      name: "７日前までは全額返金が可能",
      lang: "日本語",
      enabled: true,
      body: "体験開始の７日前まで全額返金いたします。それ以降のキャンセルは返金不可となります。",
      note: "",
      updatedAt: "2024/01/15",
    },
    {
      id: "ct_04_14DAY",
      name: "１４日前までは全額返金が可能",
      lang: "日本語",
      enabled: true,
      body: "体験開始の１４日前まで全額返金いたします。それ以降のキャンセルは返金不可となります。",
      note: "",
      updatedAt: "2024/01/15",
    },
  ],

  modes: {
    create: { label: "作成", badge: "作成中", status: "下書き", action: "下書き保存" },
    edit: { label: "編集", badge: "編集中", status: "販売準備完了", action: "更新保存" },
    review: { label: "確認", badge: "確認中", status: "公開前チェック", action: "確認完了" },
  },
};

